version = 1

[[analyzers]]
name = "sql"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[code_formatters]]
name = "black"

[[code_formatters]]
name = "autopep8"

[[code_formatters]]
name = "isort"

[[code_formatters]]
name = "standardjs"

[[code_formatters]]
name = "prettier"