# Workflow for automatically assigning issues
name: Pull request and issue auto-assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requestS: write
    steps:
      - name: Auto-assign new issues and pull requests
        uses: pozil/auto-assign-issue@6594700 # v1.14.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: 'mohavro'
          numOfAssignee: 1
