# Workflow for automatically assigning issues
name: Issue auto-assign
 on:
   issues:
     types: [opened]
+  pull_request:
+    types: [opened]
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign new issues
        uses: pozil/auto-assign-issue@6594700 # v1.14.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: 'mohavro'
          numOfAssignee: 1
